/* eslint-disable @next/next/no-img-element */
import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser();
  console.log(user);

  if(!user) return null;

  return( 
  <div className="flex gap-3 w-full">
    <Image
    width={56}
    height={56}
    src={user.profileImageUrl} 
    alt="Profile Image"
    className="h-14 w-14 rounded-full" />
    <input placeholder="Type some emojis!" className="grow bg-transparent outline-none"/>
  </div>)
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const {post, author} = props;

  return (
    <div key={post.id} className="border-b border-slate-200 p-4 gap-3 flex">
      <img 
      src={author.profileImageUrl} 
      alt="Profile Image" 
      className="h-14 w-14 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-200 font-thin gap-2">
          <span className="font-bold">{`@${author.username}`}</span><span>{`· ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span className="text-2xl">{post.content}</span>
      </div>
  </div>
  )
}

const Feed = () => {
  const {data, isLoading: postsLoading} = api.posts.getAll.useQuery();

  if(postsLoading) return <LoadingPage />

  if(!data) return <div>Something went wrong</div>

  return (
    <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
                <PostView {...fullPost} key={fullPost.post.id}/>
            ))}
          </div>
  )
}

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  //start fetching data asap
  api.posts.getAll.useQuery();

  //Return empty div if user isn't loaded yet
  if(!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-200">
          <div className="flex border-b border-slate-200 p-4">
            {!isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {isSignedIn && <CreatePostWizard />}
          </div>

          <Feed />
        </div>
      </main>
    </>
  );
}
